# site name
prefixName: 东方
siteName: 动漫社
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: https://cdn.v2ex.com/gravatar/b081852ef8e2de64dfa5520b0e3c556d?d=mp&r=g&s=300
url: https://thaclub.github.io
description: 二次元学生社团 不仅仅只是东方project
cdn: https://cdn.jsdelivr.net/gh/thaclub/thaclub@1.0
pjax: 1
# 1开启
mathjax: 0

notice: 原站正在向hexo-Sakura迁移，请等待进一步更新...
lazyloadImg: https://cdn.jsdelivr.net/gh/sldarkwd/build@6f29bbc/usr/themes/Aria/assets/img/loading.svg

menus:
  主页: { path: /, fa: fa-fort-awesome faa-shake }
  目录: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    默认: {path: /categories/生活/, fa: fa-file-text-o }, 
    安利: {path: /categories/随想/, fa: fa-commenting-o },
    原创: {path: /categories/转载/, fa: fa-book }
  } }
  留言: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友链: { path: /links/, fa: fa-link faa-shake }
  关于: { path: /, fa: fa-leaf faa-wrench  }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 6
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/sldarkwd/pictures@f0609b6/th/gg.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: 

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/322448790, title: Bilibili, desc: 社团的B站账号, img: /img/startdash/bilibili.jpg}
  - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 04/03/2019

#social  url, img PC端配置
#social:
#  github: {url: http://github.com/honjun, img: /img/social/github.png}
#  sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
#  wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
#  zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
#  email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
#  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
#  wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
#msocial:
#  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
#  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
#  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

#donate:
#  paypal: https://www.paypal.me/hojuncn
#  alipay: /img/custom/donate/AliPayQR.jpg
#  wechat: /img/custom/donate/WeChanQR.jpg
#  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/sldarkwd/ringclub@1.0
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: 3.1.1_x264.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  listFolded: true
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: 3smzzFbaocSrFHp2qEM3VbnW-gzGzoHsz
v_appKey: NNvVWYlhd18C7ECcFSH8czG3

